name: $(Date:yyyy-MM-dd-hh-mm-ss)$(Rev:.r)

trigger:
- master
- master_dev

pool: 'Default'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

workspace: 
  clean: all

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m pip install numpy
    python -m pip install scipy
    python -m pip install matplotlib
    python -m pip install "\\milky-way\projects\NSD\Mothman\AutomatedBuilds\Build Server Resources\pandas-1.4.1-cp39-cp39-win_amd64.whl"
    python -m pip install "\\milky-way\projects\NSD\Mothman\AutomatedBuilds\Build Server Resources\PyInstaller-3.6.tar.gz"
  displayName: 'Install Dependencies'
  
- script: |
    pyinstaller sensitivity_GUI.spec sensitivity_GUI.py
  displayName: 'Create Sensitivity GUI'

- script: |
    pyinstaller infrastructures_gui.spec infrastructures_gui.py
  displayName: 'Create Application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true
  displayName: 'Archive Application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SIRMExe'
    publishLocation: 'Container'
